version: '3.1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: leo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voi
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8080:8080"
